name: ice_flutter_toolkit
description: "Ledokol Flutter UI Library"
version: 0.1.5

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #Architecture Packages
  flutter_mobx: ^2.3.0                    #для стейтменеджмента
  dio: ^5.8.0+1                           #для REST/CURL запросов

  #Native Packages
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1           #для запроса разрешений
  shared_preferences: ^2.5.3              #это не защищенное хранилище общего назначения
  flutter_secure_storage: ^9.2.4          #это защищенное от чтения из вне хранилище
  connection_notifier: ^2.0.1             #для отслеживания connect-соединения

  #UI Packages
  flutter_svg: ^2.1.0                     #для векторных изображений
  cached_network_image: ^3.4.1            #для загрузки фото по url с кэшированием внутри приложения

  #Compute Packages
  phone_numbers_parser: ^9.0.3            #для валидации номера телефона любого региона

dev_dependencies:
  flutter_lints: ^3.0.1                   #линтер
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true